name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download
        go mod verify
        go get golang.org/x/tools/cmd/cover
        go get github.com/mattn/goveralls

    - name: Build
      run: ./build.sh

    - name: Test
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        DOOKER: ${{ secrets.DOOKER }}
        FOO: bar
      run: |
        echo "${DOOKER} ${FOO}"
        chmod 000 ./testdata/secret
        go test ./... -cover -coverprofile=coverage.out
        go tool cover -func coverage.out
        goveralls -coverprofile=coverage.out -service=circle-ci -repotoken "${COVERALLS_TOKEN}"

